import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { BlockItem } from ".";
import AboutBlock, { AboutBlockInterface } from "../components/AboutBlock";
import FeatureBlock, { FeatureBlockInterface } from "../components/FeatureBlock";

import PageBanner from "../components/PageBanner";
import Team, { TeamItemInterface } from "../components/Team";

interface AboutPageInterface {
  about_block: AboutBlockInterface;
  feature_block: FeatureBlockInterface;
  team_block: BlockItem;
}

interface Props extends AboutPageInterface {
  teamItems: TeamItemInterface[];
}

const About: NextPage<Props> = ({ about_block, feature_block, team_block, teamItems }) => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageBanner title={about_block.preTitle} />

      <AboutBlock aboutBlock={about_block} />

      <FeatureBlock featureBlock={feature_block} />

      <Team teamItems={teamItems} preTitle={team_block.preTitle} title={team_block.title} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/about_page");
  const about_page: AboutPageInterface = await res.json();

  const resTeam = await fetch("http://localhost:5001/team");
  const teamItems: TeamItemInterface[] = await resTeam.json();

  return {
    props: {
      about_block: about_page.about_block,
      feature_block: about_page.feature_block,
      team_block: about_page.team_block,
      teamItems,
    },
  };
};

export default About;
