import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner, { BannerInterface } from "../components/Banner";
import Services, { ServiceItemInterface } from "../components/Services";
import Team, { TeamItemInterface } from "../components/Team";

export interface BlockItem {
  preTitle: string;
  title: string;
}

interface HomepageInterface {
  banner_content: BannerInterface;
  services_block: BlockItem;
  team_block: BlockItem;
}

interface Props extends HomepageInterface {
  services: ServiceItemInterface[];
  teamItems: TeamItemInterface[];
}

const Home: NextPage<Props> = ({
  banner_content,
  services_block,
  team_block,
  services,
  teamItems,
}) => {
  return (
    <>
      <Head>
        <title>Arhitektur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner title={banner_content.title} content={banner_content.content} />

      <Services
        preTitle={services_block.preTitle}
        title={services_block.title}
        services={services}
      />

      <Team preTitle={team_block.preTitle} title={team_block.title} teamItems={teamItems} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/homepage");
  const homepage: HomepageInterface = await res.json();

  const resServices = await fetch("http://localhost:5001/services");
  const services: ServiceItemInterface[] = await resServices.json();

  const resTeam = await fetch("http://localhost:5001/team");
  const teamItems: TeamItemInterface[] = await resTeam.json();

  return {
    props: {
      banner_content: homepage.banner_content,
      services_block: homepage.services_block,
      team_block: homepage.team_block,
      services,
      teamItems,
    },
  };
};

export default Home;
