import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageBanner from "../components/PageBanner";
import Services, { ServiceItemInterface } from "../components/Services";
import Team, { TeamItemInterface } from "../components/Team";
import { BlockItem } from ".";

interface ServicesPageInterface {
  services_block: BlockItem;
  team_block: BlockItem;
}

interface Props extends ServicesPageInterface {
  services: ServiceItemInterface[];
  teamItems: TeamItemInterface[];
}

const ServicesPage: NextPage<Props> = ({ services_block, services, team_block, teamItems }) => {
  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageBanner title={services_block.preTitle} />

      <Services
        preTitle={services_block.preTitle}
        title={services_block.title}
        services={services}
      />

      <Team preTitle={team_block.preTitle} title={team_block.title} teamItems={teamItems} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/services_page");
  const servicesPage: ServicesPageInterface = await res.json();

  const resServices = await fetch("http://localhost:5001/services");
  const services: ServiceItemInterface[] = await resServices.json();

  const resTeam = await fetch("http://localhost:5001/team");
  const teamItems: TeamItemInterface[] = await resTeam.json();

  return {
    props: {
      services_block: servicesPage.services_block,
      team_block: servicesPage.team_block,
      services,
      teamItems,
    },
  };
};

export default ServicesPage;
